name: release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle build
        run: ./gradlew clean build shadowJar

      - name: Move,rename packages and get tag,version
        id: package
        run: |
          mkdir packages
          mv build/libs/*all.jar packages/
          cd packages
          
          for file in `ls|grep .jar`
          do
            newfile=`echo $file | sed 's/-all//g'`
            echo $newfile
            mv $file $newfile
          done
          
          for file in `ls|grep .jar`
          do
            var1=`echo $file | sed 's/.jar//g'`
            break
          done
          var3=`expr index $var1 '.'`
          var2=${var1:0:$var3-1}
          var2=${var2%-*}+2
          var2=`expr length $var2`
          output=`expr substr $var1 $var2 $var3`
          echo "::set-output name=VERSION::$output"
          
      - name: Github release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.package.outputs.VERSION }}"
          prerelease: true
          title: "CI automatical build ${{ steps.package.outputs.VERSION }}"
          files: |
            packages/*.jar
            packages/*.apk
